#!/usr/bin/env bash

#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS	     #
#                                   #
#####################################

# About Exodia OS #

# Get ISO Version #
if [[ -e '/version' ]]; then
	VERSION="v`cat /version | cut -d'.' -f1`.`cat /version | cut -d '.' -f2`"
else
	VERSION='rolling'
fi

yad --title='About Exodia OS' --window-icon='exodia-cyan' \
	--about \
	--pname='Exodia OS' \
	--pversion="${VERSION}" \
	--image='exodia-cyan' \
	--comments="A highly customized arch-based distro For All Cybersecurity fields.
	It comes with other special editions as well. 
	Proudly developed in Egypt 🇪🇬 by Cyb3rTh1eveZ Team." \
	--copyright="00xWolf | Cyb3rTh1eveZ Team  﫥  Copyrights 2022-`date +'%Y'`,
	Mahmoud Mohamed:- 
	  :@mmsaeed509  |   :@mmsaeed509" \
	--license='GPL3' \
	--website='https://exodia-os.github.io/exodia-website/' \
	--website-label='visit Exodia OS' \
	--authors="Mahmoud Mohamed <https://github.com/mmsaeed509>  﫥  Cyb3rTh1eveZ Team" \
	--fontname='JetBrainsMono Nerd Font 16'
